### ISSUE TITLE
Find correct rfm9x library without V3Rex modifications

### ISSUE THREAD

**Issue by thetazero** [PyCubed-Mini/flight_software#159]

**Comment by yashika-batra** [comment]
I have a copy of this here: 
https://github.com/PyCubed-Mini/feather-groundstation/blob/system-check-script/system-check/lib/adafruit_rfm9x.py

And here's the original:
https://docs.circuitpython.org/projects/rfm9x/en/latest/

**Comment by thetazero** [comment]
Yeah, I believe the default rfm9x library doesn't play nice with tasko however. So Max modified it. 
This is worth looking into though.

**Comment by yashika-batra** [comment]
Isn't the [pycubed_rfm9x](https://github.com/PyCubed-Mini/flight_software/blob/main/basic/lib/pycubed_rfm9x.py) file Max's modification? It was created to work with the beepsat's event based task loop, which uses tasko if I remember correctly.

**Comment by thetazero** [comment]
Yeah, but his modifications didn't work at all unfortunately.

**Comment by thetazero** [comment]
Found and modified, just using adafruit's rfm9x library
