### ISSUE TITLE
Sun zp sensor is initialized but left unused in pycubedmini.py

### ISSUE THREAD

**Issue by thetazero** [PyCubed-Mini/flight_software#17]
In line 153 of [pycubedmini.py](https://github.com/PyCubed-Mini/software_example_beepsat/blob/main/advanced/lib/pycubedmini.py#L153)

**Comment by yashikabatra15** [comment]
I talked to Jacob about this, and we're going to leave it initialized but unused, as that makes it available for future use (should we ever need the sun sensor initialized for future updates).

**Comment by thetazero** [comment]
We can do this later but it's still an issue.
