### ISSUE TITLE
Large file transfer/download

### ISSUE THREAD

**Issue by jbwillis** [PyCubed-Mini/flight_software#188]

**Comment by thetazero** [comment]
The transmission/radio side of this is done. I'd like to do the following things though:
- [ ] Write the file to some certain spot by default. Perhaps `/sd/download`
- [ ] Write the file in parts to the SD card by using append mode
- [ ] Add a message type that reads from SD chunk by chunk
- [ ] Add a command for move/delete SD operations
- [ ] Add a command to request hash from certain file on SD card
- [ ] Add a command to request a listdir from a certain directory
