### ISSUE TITLE
Real Time Clock Software integration

### ISSUE THREAD

**Issue by jbwillis** [PyCubed-Mini/flight_software#198]
Need an interface to the RTC with the following capabilities
- [x] Update the RTC from the ground
- [x] Read the value of the RTC
- [ ] Should we couple this with the circuitpython time library somehow??? Seems like it might be best to keep them separate
- [ ] All code should reference the RTC time rather than the circuitpython time
- [ ] Test updating the time ahead/behind the current time and see what happens

**Comment by thetazero** [comment]
RTC interface is complete for our purposes.
