### ISSUE TITLE
Logging for imu task isn't pretty

### ISSUE THREAD

**Issue by jefferyjohn** [PyCubed-Mini/flight_software#211]
Format numpy arrays into strings nicely

**Comment by amoghrajesh** [comment]
@jefferyjohn is this issue still open. I would like to take it up for Hacktoberfest 2022.

**Comment by jefferyjohn** [comment]
@amoghrajesh yes, but we're still setting up Hacktoberfest eligibility. We'll have more issues appear soon with their tag!
