### ISSUE TITLE
Rename Tasks/*_task.py to Tasks/*.py for consistency

### ISSUE THREAD

**Issue by thetazero** [PyCubed-Mini/flight_software#386]
Other way around is also fine, just want consistency.

**Comment by Ankit8848** [comment]
@thetazero can u provide the code base where i have to change .it will be helpful.

**Comment by thecuriousjuel** [comment]
Hello @thetazero, I saw this open issue and I want to contribute to this change. Can you add me as a participant?

**Comment by Ankit8848** [comment]
@thecuriousjuel go on, I am not working on it  .

**Comment by thecuriousjuel** [comment]
I created the PR - https://github.com/PyCubed-Mini/flight_software/pull/387

Waiting for the review process.
